#!/usr/bin/env bash
# displaying information of the school file

file_r=./school
if [ -e "$file_r" ];
then
echo "school file exists"
if [ -s "$file_r" ];
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "$file_r" ];
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
